version: '3'
services:
  backend:
    image: backend-image
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - backend-data:/app/data
    environment:
      - NODE_ENV=production
    restart: always
  frontend:
    image: frontend-image
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - frontend-data:/app/data
    environment:
      - NODE_ENV=production
    restart: always
volumes:
  backend-data:
  frontend-data: