version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tracker-backend
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this-in-production}
      - DATABASE_PATH=/app/data/jobtracker.db
      - UPLOAD_FOLDER=/app/uploads
    volumes:
      - backend-data:/app/data
      - backend-uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tracker-frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data:
    driver: local
  backend-uploads:
    driver: local
